### PR TITLE
fix auto-merge for 1.0.5 release branch

### PR DESCRIPTION
**Pull request by neetopia**

### CODE REVIEW

**Comment by ting-yuan** [comment]
This commit is missing. Do you expect auto-merger to merge it?

commit 6c906beef9720a431343914c523d700af9c510a6
Author: Jiaxiang Chen <jiaxiang@google.com>
Date:   Mon Mar 21 22:41:44 2022 -0700

    * Extract CodeGeneratorImpl, PlatformInfoImpl into common-util module, add copyright to common-util module classes.
    * Add KSP Command line processor and logger.
    * Implement KSP main execution and initialization logic.

**Comment by neetopia** [comment]
No, I will need to fix it

**Comment by neetopia** [comment]
although it is not really needed for 1.0.5 release branch.. but I will include it anyways.

**Comment by ting-yuan** [comment]
Yeah, merging it is better. Auto-merger will try and maybe fail otherwise.

**Review by ting-yuan — APPROVED** [review]

**Pull request merged**
