### PR TITLE
AGP callback only once app/lib/dynamic-feature plugin is applied

### LINKED ISSUE #314: Build failing when trying to add the plugin on an Android module
I'm following the quickstart guide step by step trying to converty my annotation processor from kapt to ksp. 
I'm doing this in a new project so there are no conflicts between kapt and ksp
 
When I try to implement the plugin I receive the following exception:

`Extension of type 'CommonExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, KspExtension]
`

I don't really know if it's important but I'm trying to implement it in an Android module. 

These are my plugins in the android module.

`plugins {
    id("com.google.devtools.ksp") version "1.4.30-1.0.0-alpha02"
    id("com.android.application")
    kotlin("android")
}`

If any information is needed I'll be happy to provide and the entire project in its current state is available here.
https://github.com/gilgoldzweig/Gencycler/tree/v3

### PR DESCRIPTION
**Pull request by gavra0**
AGP "com.android.base" plugin is applied before the AGP extension
is created, so it is too early to access it. This change waits for
application, library, or dynamic-feature plugins to be applied before
decorating the extension.

Fixes #314

### CODE REVIEW

**Review by ting-yuan — APPROVED** [review]
Rubber stamping here. I'll try to test with the repro cases before merging.

**Comment by ting-yuan** [comment]
Seems having problem with the [playground-android.zip](https://github.com/google/ksp/files/5959489/playground-android.zip) in #35 

```
java.lang.NoSuchMethodError: 'org.gradle.api.NamedDomainObjectContainer com.android.build.api.dsl.CommonExtension.getSourceSets()'
        at com.google.devtools.ksp.gradle.AndroidPluginIntegration$decorateAndroidExtension$1.execute(AndroidPluginIntegration.kt:66)
            at com.google.devtools.ksp.gradle.AndroidPluginIntegration$decorateAndroidExtension$1.execute(AndroidPluginIntegration.kt:37)
            at org.gradle.internal.extensibility.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:173)
            at org.gradle.internal.extensibility.ExtensionsStorage.configureExtension(ExtensionsStorage.java:70)
            at org.gradle.internal.extensibility.DefaultConvention.configure(DefaultConvention.java:189)
            at org.gradle.internal.extensibility.DefaultConvention.configure(DefaultConvention.java:184)
            at com.google.devtools.ksp.gradle.AndroidPluginIntegration.decorateAndroidExtension(AndroidPluginIntegration.kt:64)
            at com.google.devtools.ksp.gradle.AndroidPluginIntegration.access$decorateAndroidExtension(AndroidPluginIntegration.kt:37)
            at com.google.devtools.ksp.gradle.AndroidPluginIntegration$applyIfAndroidProject$$inlined$forEach$lambda$1.execute(AndroidPluginIntegration.kt:47)
            at com.google.devtools.ksp.gradle.AndroidPluginIntegration$applyIfAndroidProject$$inlined$forEach$lambda$1.execute(AndroidPluginIntegration.kt:37)
            at org.gradle.api.internal.plugins.DefaultPluginManager$3.execute(DefaultPluginManager.java:252)
            at org.gradle.api.internal.plugins.DefaultPluginManager$3.execute(DefaultPluginManager.java:249)
            at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1$1.run(DefaultCollectionCallbackActionDecorator.java:100)
```

**Comment by ting-yuan** [comment]
Updating AGP to 4.2.0-beta04 makes the error disappear. Might be useful to do some version check in `KspGradleSubplugin.isApplicable()`.

**Comment by yigit** [comment]
> Updating AGP to 4.2.0-beta04 makes the error disappear. Might be useful to do some version check in `KspGradleSubplugin.isApplicable()`.

If agp has an api to get the version, it is probably better to check it in the android integration helper.

We can probably also add support for older versions but i don't think it is worth it since ksp is still alpha and agp 4.2 is in beta

**Review by yigit — APPROVED** [review]
Thanks!

**Comment by gavra0** [comment]
`CommonExtension.sourceSets` was added in AGP 4.1. I've added support for AGP 4.0 and below in the PR as well.

**Pull request merged**
