### PR TITLE
Add DeeplinkDispatch Github Link to README

### PR DESCRIPTION
**Pull request by chrisjenx**

### CODE REVIEW

**Comment by chrisjenx** [comment]
@googlebot  I signed it

**Review by neetopia — APPROVED** [review]
Thanks for supporting KSP!

BTW there is a conflict, I'll merge this PR once it is resolved.

**Comment by neetopia** [comment]
somehow it is still showing conflict, can you try to do a rebase & force push again?

**Comment by ZacSweers** [comment]
@neetopia maybe look again? Github's UI often needs a forced refresh (cmd+shift+R) to actually show updated status, I've been misled by it a lot and don't see any conflicts on this PR.

**Comment by chrisjenx** [comment]
Looks like to me there is no conflict?

**Comment by ting-yuan** [comment]
It's showing conflict to me as well and the **Rebase and merged** button is grayed out. @neetopia can we merge and push manually?

**Comment by neetopia** [comment]
Oh I think it might be because there is a merge commit in this PR, if I switch to squash and merge or create a merge commit it will work.

**Pull request merged**
