### PR TITLE
Introduce asMemberOf to KSPropertyDeclaration and KSFunctionDeclaration

### LINKED ISSUE #208: Make `asMemberOf` an extension function
Right now it is a member of `Resolver`:
```
fun asMemberOf(
    property: KSPropertyDeclaration,
    containing: KSType
): KSType
```
Should be more *Kotlin* if:
```
fun KSPropertyDeclaration.asMemberOf(
    containing: KSType,
): KSType
```

### PR DESCRIPTION
**Pull request by ting-yuan**
They are more convenient and object oriented.

fixes #208

### CODE REVIEW

**Comment by neetopia** [comment]
should the original extension function be removed then?

**Review by neetopia — APPROVED** [review]

**Comment by ting-yuan** [comment]
> should the original extension function be removed then?

which extension function?

**Comment by neetopia** [comment]
I mean `Resolver.asMemberOf()`, could make it internal since it is same as the member functions from this PR.

**Comment by ting-yuan** [comment]
Make sense. Please take a look again.

**Review by neetopia — APPROVED** [review]

**Pull request merged**
