### PR TITLE
change the modifiers to private from public and lift return out of 'if'

### PR DESCRIPTION
**Pull request by heli-os**
Hi i am Heli who using ksp.

~First, changed some codes to not use the platform type. platform type requires unnecessary boilerplate(!!, let trick, ...) And open source is a guide to writing code.~

~so i think bad code examples should be deleted.~

Second, Lift return out of 'if'

Third, change the modifiers to private from public

thanks. 🙇

--
There is no change that users can feel.

### CODE REVIEW

**Comment by heli-os** [comment]
Can anyone please review it?

**Comment by neetopia** [comment]
I think the change for combining return statement and private val make sense to me, but I don't get the benefit of adding explicit types to the rest of your change, if no specific reasons, maybe let's not touch them.

**Comment by heli-os** [comment]
@neetopia 
okay, It would be better not to touch it.

I removed the added explicit type.

**Comment by neetopia** [comment]
Thanks for your PR!

**Pull request merged**
